version: '3.8'
services:
  easydash:
    build: .
    image: easydash:latest
    container_name: easydash_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - test_wp_wordpress_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.easydash.rule=Host(`devjee.gauthier-nicolas.fr`)"
      - "traefik.http.routers.easydash.entrypoints=websecure"
      - "traefik.http.routers.easydash.tls.certresolver=letsencrypt"
      - "traefik.http.services.easydash.loadbalancer.server.port=3000"

networks:
  test_wp_wordpress_network:
    external: true